# Generated by Django 4.1.4 on 2023-01-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_reply_user_reply_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liketweets', to='hello.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeusers', to='hello.user')),
            ],
        ),
    ]
