# Generated by Django 4.1.4 on 2023-01-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_likeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeuser',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lt', to='hello.tweet'),
        ),
        migrations.AlterField(
            model_name='likeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lu', to='hello.user'),
        ),
    ]
