# Generated by Django 4.1.4 on 2023-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_likeforreply_likefortweet_delete_likeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='heart',
            field=models.CharField(default='❤', max_length=1),
        ),
        migrations.AddField(
            model_name='tweet',
            name='heart',
            field=models.CharField(default='❤', max_length=1),
        ),
    ]
