# Generated by Django 4.1.4 on 2023-01-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20230105_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='heart',
        ),
    ]
